### ISSUE TITLE
Styling Ticket Content

### ISSUE THREAD

**Issue by y-ack** [ilovecherries/pBox#3]
apart from a consideration of ticket expand lightboxes, etc, the following markup/styling changes are recommended:
![image](https://user-images.githubusercontent.com/12588017/150720073-49f7ad66-ad19-4a6a-a87a-895d263488f0.png)
 - wrap the main card text in a `div.text-primary`
```css
.text-primary {
  white-space: pre-wrap;
  max-height: 10rem;
  overflow-y: auto;
}
```
(maybe some borders/padding for niceness or something)

![image](https://user-images.githubusercontent.com/12588017/150720538-eca2a50f-c138-4bab-b7e0-c52a33eb3dbf.png)
